### ISSUE TITLE
Does this work for mac-os/arm64?

### ISSUE THREAD

**Issue by samirtahir91** [medyagh/setup-minikube#437]
Hi

I've been using this in a matrix job, in ubuntu and mac os. Recently the mac os job fails with default step:

Step:
```yaml
      - name: Setup Minikube cluster
        uses: medyagh/setup-minikube@latest
```

```
Run medyagh/setup-minikube@latest
/bin/chmod +x /Users/runner/work/_temp/3b689e38-15aa-4ed2-b248-49083[7](https://github.com/samirtahir91/github-app-operator/actions/runs/8791099664/job/24240357474#step:5:8)7d54f4
/Users/runner/bin/minikube version --short
╭──────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                                          │
│    You are trying to run the amd64 binary on an M1 system.                                               │
│    Please consider running the darwin/arm64 binary instead.                                              │
│    Download at https://github.com/kubernetes/minikube/releases/download/v1.33.0/minikube-darwin-arm64    │
│                                                                                                          │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────╯
v1.33.0
Error: Key Validation Error: iso-

╭──────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                                          │
│    You are trying to run the amd64 binary on an M1 system.                                               │
│    Please consider running the darwin/arm64 binary instead.                                              │
│    Download at https://github.com/kubernetes/minikube/releases/download/v1.33.0/minikube-darwin-arm64    │
│                                                                                                          │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────╯
v1.33.0-arm64 cannot be larger than 512 characters.
/Users/runner/work/_actions/medyagh/setup-minikube/latest/dist/index.js:432
        throw new ValidationError(`Key Validation Error: ${key} cannot be larger than 512 characters.`);
              ^

ValidationError: Key Validation Error: kic-

╭──────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                                          │
│    You are trying to run the amd64 binary on an M1 system.                                               │
│    Please consider running the darwin/arm64 binary instead.                                              │
│    Download at https://github.com/kubernetes/minikube/releases/download/v1.33.0/minikube-darwin-arm64    │
│                                                                                                          │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────╯
v1.33.0-arm64 cannot be larger than 512 characters.
    at checkKey (/Users/runner/work/_actions/medyagh/setup-minikube/latest/dist/index.js:432:15)
    at /Users/runner/work/_actions/medyagh/setup-minikube/latest/dist/index.js:469:13
    at Generator.next (<anonymous>)
    at /Users/runner/work/_actions/medyagh/setup-minikube/latest/dist/index.js:399:71
    at new Promise (<anonymous>)
    at __webpack_modules__.7799.__awaiter (/Users/runner/work/_actions/medyagh/setup-minikube/latest/dist/index.js:395:12)
    at restoreCache (/Users/runner/work/_actions/medyagh/setup-minikube/latest/dist/index.js:459:12)
    at /Users/runner/work/_actions/medyagh/setup-minikube/latest/dist/index.js:66:37
    at Generator.next (<anonymous>)
    at /Users/runner/work/_actions/medyagh/setup-minikube/latest/dist/index.js:15:71

Node.js v20.[8](https://github.com/samirtahir91/github-app-operator/actions/runs/8791099664/job/24240357474#step:5:9).1
```

**Comment by medyagh** [comment]
@samirtahir91 I think you are right that is a legit bug, it is hard coded for amd ! I would accept a PR that fixes

**Comment by samirtahir91** [comment]
This is the github agent not self gosted
